### ISSUE TITLE
Add a link to "Storage Provider" tutorial from a respective section in the root README

### ISSUE THREAD

**Issue by siman** [Joystream/helpdesk#12]
Point to https://github.com/Joystream/helpdesk/tree/master/roles/storage-providers from https://github.com/Joystream/helpdesk#storage-providers

**Comment by bwhm** [comment]
Good point. I'll add links to guide for all roles!

**Comment by siman** [comment]
I see that there is a link on the top of the root README, but it will help to repeat this link again in a respective section.

**Comment by bwhm** [comment]
Fully agree

**Comment by siman** [comment]
It also makes sense to add an SEO-optimized title to this page:
 https://github.com/Joystream/helpdesk/tree/master/roles/storage-providers

for example: `"How to become a storage provider on Joystream"`, so people could easily find it when googling. And similar titles for other roles.
