### ISSUE TITLE
Change instructions link

### ISSUE THREAD

**Issue by TheLifeGamingYT** [Joystream/helpdesk#14]
Hi!
I found in the Storage Provider tutorial that the link that redirects to the tutorial of the setup of the node is incorrect. The correct link is https://github.com/Joystream/helpdesk/tree/master/roles/validators.
Hope to be helpful!
TheLifeGamingYT

**Comment by finnyfound** [comment]
Yes, i just stumbled on it.
please recheck links at
https://github.com/Joystream/helpdesk/tree/master/roles/storage-providers#run-a-joystream-node

**Comment by bwhm** [comment]
Thanks guys! Will fix asap!
