### ISSUE TITLE
Cmdtest getting installed instead of yarn

### ISSUE THREAD

**Issue by finnyfound** [Joystream/helpdesk#16]
if i run command
```
# On Linux
$ sudo apt-get install npm yarn nodejs git build-essential
```
![image](https://user-images.githubusercontent.com/31723998/56434248-6a34db00-62f1-11e9-8fba-ec6f738471a6.png)

yarn will be changed to cmdtest and get installed.

and later results in
```
joy@joy:~/storage-node-joystream$ yarn run build
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'run
```
![image](https://user-images.githubusercontent.com/31723998/56434299-a9fbc280-62f1-11e9-858b-84938eba96bb.png)

**Comment by bwhm** [comment]
Hey @finnyfound 
what distro are you using? was it fresh a instance from AWS or similar?

**Comment by bwhm** [comment]
try:
```
$ sudo apt-get update && sudo apt-get upgrade
$ sudo apt-get remove cmdinstall cmdtest
# not access to linux atm, not sure if one or both works
$ sudo apt-get install yarn
```

**Comment by finnyfound** [comment]
sorry i didnt mention  that
i was trying to install in my vm first 
using **Ubuntu Server 18.04.2 LTS**

**Comment by finnyfound** [comment]
log cmdinstall was not there. removed cmdtest
ran install yarn
same result(cmdtest got installed)

```
joy@joy:~/storage-node-joystream$ sudo apt-get update && sudo apt-get upgrade
[sudo] password for joy:
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Fetched 252 kB in 3s (87.7 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
joy@joy:~/storage-node-joystream$ sudo apt-get remove cmdinstall cmdtest
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package cmdinstall
joy@joy:~/storage-node-joystream$ sudo apt-get remove  cmdtest
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  python-chardet python-cliapp python-markdown python-pygments python-ttystatus python-yaml
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  cmdtest
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 98.3 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 77497 files and directories currently installed.)
Removing cmdtest (0.32-1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
joy@joy:~/storage-node-joystream$ sudo apt-get install yarn
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'cmdtest' instead of 'yarn'
The following NEW packages will be installed:
  cmdtest
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/21.1 kB of archives.
After this operation, 98.3 kB of additional disk space will be used.
Selecting previously unselected package cmdtest.
(Reading database ... 77472 files and directories currently installed.)
Preparing to unpack .../cmdtest_0.32-1_all.deb ...
Unpacking cmdtest (0.32-1) ...
Setting up cmdtest (0.32-1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...

```

**Comment by bwhm** [comment]
Ok. think I got it now:
```
$ sudo apt-get remove cmdtest
$ sudo apt autoremove
$ sudo apt-get update
$ sudo apt-get install yarn
```

**Comment by finnyfound** [comment]
same, followed your commands "cmdtest" is getting installed.
i will try manual install explained here
https://github.com/yarnpkg/yarn/issues/3189#issuecomment-384556461

**Comment by finnyfound** [comment]
I was able to install manually

also someone can follow this method if needed.


This also works

```
sudo apt remove cmdtest
sudo apt remove yarn
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install yarn
```

**Comment by bwhm** [comment]
Thanks for your help! I'll close this now, and update the helpdesk!

**Comment by bwhm** [comment]
Keeping it closed, but feel free to DM me XMR address for bounty :)

**Comment by mlncn** [comment]
In Debian testing (and Ubuntu 20.10), you can install a the yarn you expect with yarnpkg (1.22.10) package with:

```bash
sudo apt install yarnpkg
```

Per https://github.com/yarnpkg/yarn/issues/3189#issuecomment-846389712

**Comment by pathaksa** [comment]
> I was able to install manually
> 
> also someone can follow this method if needed.
> 
> This also works
> 
> ```
> sudo apt remove cmdtest
> sudo apt remove yarn
> curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
> echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
> sudo apt-get update && sudo apt-get install yarn
> ```

This worked for me

**Comment by lamtom1** [comment]
I found this helpful


$ sudo apt-get update && sudo apt-get upgrade
$ sudo apt-get remove cmdinstall cmdtest
# not access to linux atm, not sure if one or both works
$ sudo apt-get install yarn

thanks a lot .

**Comment by desarrollosrosarinos** [comment]
> Ok. think I got it now:
> 
> ```
> $ sudo apt-get remove cmdtest
> $ sudo apt autoremove
> $ sudo apt-get update
> $ sudo apt-get install yarn
> ```

Thank you, i need this.
