### ISSUE TITLE
WIP: KB for Joystream Node Athens Release

### ISSUE THREAD

**Issue by sqyuid** [Joystream/helpdesk#26]
This links to a knowledge base document to help users with common Joystream node issues.
https://github.com/Joystream/substrate-node-joystream/issues/71

**Comment by bwhm** [comment]
I think a lot of these fits quite nicely under the [troubleshooting](https://github.com/Joystream/helpdesk/tree/master/roles/validators#troubleshooting) section of this repo.

If you could submit a PR incorporating these changes, and improving/adding to other parts as well, this would obviously qualify for a rewards.

**Comment by bwhm** [comment]
Closing this, as it's outdated.
