### ISSUE TITLE
issue starting storage Provider

### ISSUE THREAD

**Issue by b0atman** [Joystream/helpdesk#27]
system : latest ubuntu-18.04.2 
issue: js_storage not starting but $ js_storage --help outputs normally. 
See images for more info:

$ yarn run build
#givers no errors 

$ npm install -g
#givers no errors 

![image](https://user-images.githubusercontent.com/50300732/57416581-d149ff00-71ce-11e9-9964-b632dbfdab11.png)

![image](https://user-images.githubusercontent.com/50300732/57416496-9b0c7f80-71ce-11e9-8ed4-3f08ca081dba.png)

**Comment by bwhm** [comment]
Hey,
Sorry for the late reply, and thanks for reporting! It's a bit to debug without knowing what other steps you have gone through, but could you do the following (inside the folder):

```
$ yarn -v
$ apt show yarn
$ git show head
```

Thanks.

**Comment by b0atman** [comment]
I fallowed the instructions to the best of my ability.  here are the outputs you asked for. thank you for the help. this was on a resent install of Ubuntu. also this OS is in a virtual machine.  

`yarn -v
1.16.0
`
apt show yarn
`Package: yarn
Version: 1.16.0-1
Priority: optional
Section: devel
Maintainer: Yarn Developers <yarn@dan.cx>
Installed-Size: 5,001 kB
Recommends: nodejs
Conflicts: nodejs (<< 4.0.0), cmdtest
Homepage: https://yarnpkg.com/
Download-Size: 837 kB
APT-Manual-Installed: yes
APT-Sources: https://dl.yarnpkg.com/debian stable/main amd64 Packages
Description: Fast, reliable, and secure dependency management.
 Yarn: Fast, reliable, and secure dependency management.
 .
 Fast: Yarn caches every package it downloads so it never needs to again. It
 also parallelizes operations to maximize resource utilization so install times
 are faster than ever.
 .
 Reliable: Using a detailed, but concise, lockfile format, and a deterministic
 algorithm for installs, Yarn is able to guarantee that an install that worked
 on one system will work exactly the same way on any other system.
 .
 Secure: Yarn uses checksums to verify the integrity of every installed package
 before its code is executed.

N: There are 45 additional records. Please use the '-a' switch to see them.
`
git show head
`sudo git show head
fatal: ambiguous argument 'head': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
amd@amd:~/storage-node-joystream$ 
`


here are the commands I used and there outputs of the important ones.  

sudo apt-get install npm yarn nodejs git build-essential libtool automake autoconf 

cd
git clone https://github.com/Joystream/storage-node-joystream.git
cd storage-node-joystream
yarn run build
`yarn run v1.16.0
$ ./build.sh
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ /home/amd/storage-node-joystream/node_modules/.bin/tsc --build tsconfig.json
Done in 3.10s.
`

`sudo npm install -g
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
/usr/local/bin/js_storage -> /usr/local/lib/node_modules/joystream-storage/bin/cli.js
/usr/local/lib
└─┬ joystream-storage@0.1.0 
  └─┬ @polkadot/api@0.76.1
    └─┬ @polkadot/rpc-rx@0.76.1
      └── rxjs@6.5.2 
`

js_storage --help # This lists the proper output.

**Comment by bwhm** [comment]
```
yarn -v 1.16.0
apt show yarn
Package: yarn
Version: 1.16.0-1
```

Ok, this looks correct. I assumed you hadn't actually gotten the "correct" yarn, as that has been an issue before. `js_storage --help` will still work after `npm install -g` even if `yarn run build` doesn't.

```
cd
git clone https://github.com/Joystream/storage-node-joystream.git
cd storage-node-joystream
yarn run build
```

This looks correct, and the output as well. Did you then just `js_storage`, or the full `js_storage signup /path/to/5YourJoyMemberAddress.json`?

If you have signed up in the [pioneer](https://testnet.joystream.org/athens/pioneer/#/accounts) and become a member, you need to make sure to pass in the correct path.

**Comment by b0atman** [comment]
**input line:**
`~/storage-node-joystream$ js_storage signup ~/storage-node-joystream/Storage_5HDHZQyuBZZiX7yThA2SzPBW2xVKk6v6dgCnQDiRABkqfdpY.json'
**output line:**
'/usr/local/lib/node_modules/joystream-storage/bin/cli.js:412
    ret.catch(console.error).finally(_ => process.exit());
                                    ^

TypeError: ret.catch(...).finally is not a function
    at Object.signup (/usr/local/lib/node_modules/joystream-storage/bin/cli.js:412:37)
    at Object.<anonymous> (/usr/local/lib/node_modules/joystream-storage/bin/cli.js:418:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3`

**Comment by jfinkhaeuser** [comment]
Sorry, what node version is this? Promises have the `.catch()` function on all platforms. I don't think it changes much, but it'll be good to know anyway.

```bash
$ node --version
```

**Comment by b0atman** [comment]
:~/storage-node-joystream$ node --version
v8.10.0

**Comment by jfinkhaeuser** [comment]
Thanks! I'm developing on `v10.15.3`, so I'd try a `v10` or above if you can. There might well be another error afterwards, but the later versions should at least implement `catch()`.

**Comment by bwhm** [comment]
just a to you @b0atman :
all ten spots are already taken, so even if you do solve the problem, you will not actually become a storage provider.

If you are able to reach the last step, I'll ship a $20 bounty anyway!

**Comment by bwhm** [comment]
Closing this, as we are in the process of re-writing the software anyway.

**Comment by b0atman** [comment]
Sorry, it's taking me a while to get back to this thread because I've encountered a plethora of other issues. I wanted to document them properly.

Essentially, I've not found a version of node that works. 

I look forward to trying the next version of the software. Hopefully it will work for me. :-)

**Comment by bwhm** [comment]
@b0atman 
Let me know what you uncovered, if you did the work, we will still honor to bounty...

**Comment by b0atman** [comment]
Thank you very much @bwhm!

@jfinkhaeuser I have updateded to `v10.15.3`
when trying to build the I get this error: [I was able to Fix it some how]
[place holder for pic]

Next issue is: [new error with node v10]
[place holder for pic]

**Comment by bwhm** [comment]
I see. This is a recurring problem using npm on linux, at least on Ubuntu... It's a not straightforward to set up npm without relying on `sudo`.

Seeing as our next storage system will also rely on npm, I will update the guide with a cleaner way of getting it work.

Considering your efforts, post your XMR address, and I'll drop you a $10 bounty. I know this is not much for the time you must have spent, but the whole npm thing is really out of our hands...

**Comment by jfinkhaeuser** [comment]
Maybe we should just include a section on how you can set up node and yarn.

It's not really a problem using npm on Linux/Ubuntu as much as it is a problem with the system packages conflicting with newer packages, so it's usually best to ignore the system packages - i.e. install node cleanly from scratch. It applies the same to e.g. Python, Perl, etc. Ubuntu tries to be a little too helpful here.

**Comment by bwhm** [comment]
> Maybe we should just include a section on how you can set up node and yarn.

As stated in the comment above yours, I'm already doing it :) I'm going to make you review later.
 
> It's not really a problem using npm on Linux/Ubuntu as much as it is a problem with the system packages conflicting with newer packages, so it's usually best to ignore the system packages - i.e. install node cleanly from scratch. It applies the same to e.g. Python, Perl, etc. Ubuntu tries to be a little too helpful here.

I'm aware of this, but besides `node` and `yarn` (that have been the source of most issues in this repo), this is outside of our scope.

**Comment by b0atman** [comment]
yes a setup guide on ubuntu for yarn and node would be good. I will be looking for it in the next testnet. 

Monaro Key: 49uvtZJU2xqSh23cbLDQVBK5332wQtVJ86MhsEFMcGAKTZpwxFtYFXkZGKrXEeVUrp67MB7xBJoqqCayri9tW93w9yz6Jz7
