### ISSUE TITLE
Fix for Debian 9.8 libssl dependency issues (libssl.so.1.0.0)

### ISSUE THREAD

**Issue by sqyuid** [Joystream/helpdesk#52]
I'm running Debian 9.8 (x64) and joystream-node requires libssl.so.1.0.0. The program will fail to launch with the error:
`./joystream-node: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`

apt-file find libssl.so results (to show that a symlink won't work in general for this issue):
`libssl-dev: /usr/lib/x86_64-linux-gnu/libssl.so
libssl1.0-dev: /usr/lib/x86_64-linux-gnu/libssl.so
libssl1.0.2: /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
libssl1.1: /usr/lib/x86_64-linux-gnu/libssl.so.1.1`

The method I've found easiest to get this library without symlink is as follows:
```
wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u11_amd64.deb
dpkg -i libssl1.0.0_1.0.1t-1+deb8u11_amd64.deb
```

If there is an appropriate troubleshooting section this could help new users to easily remedy this issue.

**Comment by bwhm** [comment]
Hey @sqyuid ,
As @mnaamani stats above, I had this issue with Debian 8, but a fresh image of Debian 9 worked for me (tested again). Is there a chance you tried the armv7 binary?

**Comment by bwhm** [comment]
Closing this as it's outdated...
