### ISSUE TITLE
Video Format Issues

### ISSUE THREAD

**Issue by mochet** [Joystream/helpdesk#61]
User requested help in a support channel for a video not playing after upload. This happened twice with different formats.

Videos uploaded:
- https://testnet.joystream.org/#/media/videos/753
- Format: XVID (mpeg-4)
- https://testnet.joystream.org/#/media/videos/755
- Format: mpeg 1/2 (mpgv)

* Currently the UI on upload page makes no mention of formatting, only that file size is < 500 MB
* Error message from player is not helpful, it only shows "Video load failed"
* The current info about formatting is from 1 year ago, is this still current? https://github.com/Joystream/bounties/issues/13

**Comment by phibosGit** [comment]
Error loading media content
Error: Unable to reach any provider serving this content

For me this is the message.

**Comment by mochet** [comment]
> Error loading media content
> Error: Unable to reach any provider serving this content
> 
> For me this is the message.

Hey, this is an issue caused by no storage provider being available currently. There was a change in how storage providers work, so there is only one storage provider hosting all the content for now, which means it maybe had a short downtime.
