### ISSUE TITLE
Stuck, Delayed and Failed Transactions

### ISSUE THREAD

**Issue by mochet** [Joystream/helpdesk#63]
Rarely a user will encounter a situation where one of two things happens, either a transaction remains at the broadcast stage for an extended period of time, or they will encounter a different error regarding the nonce.

I just tried to make a token transfer and encountered a stuck transaction.

This is what the user sees (for quite some time). There is no way to cancel the transaction or troubleshoot it.
![image](https://user-images.githubusercontent.com/50830161/83872697-8c7ef780-a743-11ea-99a8-32515920bc48.png)

This is the console output from the browser:
```makeExtrinsicCall: extrinsic :: 0xa0040500ff1fcd1c1dcf2b993912d6a07e9f05b1c9de768f9d32b891bc157117659401bc0882380100
main.dc966f9e.js:108 makeExtrinsicCall: updated status :: {"events":[],"status":{"Ready":null}}
main.dc966f9e.js:108 makeExtrinsicCall: updated status :: {"events":[],"status":{"Broadcast":["QmPngPhzFSTastJE4WfS5yfgFstd71ATVyKiU62b3SBcgN","QmbC54kzb44f9yGgNyJN2em189a3YmavuWuKaYja5rWv6a","QmRqisGrs9RHuS7X3bMVb8RG4Z6GnQtQd9nxAQgQdAoN9o","QmNQhsrjJnFnc5DSPGGWEbCzH2q7oCsmxHXEJDqnodw28p","QmU2mFp5kdzKzKT83hRWyYQuVP6ESEpxLh8YWrXkTLFBPz","QmWb8gSs2dZfbzWCegj7Mx85vDZLgfoNV44h1FLqvaqn2C","Qmb4ptSyBtCm11AXaG7dyiMEiHbn1VujtLdCpJrf9SD5Gh","QmRb5e6sKH9bR2Cg1ndR642ZRaytCCMciaiUaR4kMjgm1s","QmQ4tMC3A29LPGowDSwQu7pbi4zfsKnqHEaLoCyyCmDzNF","QmWkUn5A5ZQ3Bmcvnc2Y8HUXidr2b6fo3j5x2Z1fiNgzt1","QmeazkudCRT3QSY7bHZvEqsyEEhqB4Wqh2XzATSUasM8w1","QmYYgAGmB926N48KqUVWTdkqPVEPfbBxyBc6fjHVWktMM7","QmYANhLjKnu9iUrcWmNP2YnBuds7p1Xxk4wrdcNrD8qMSh","QmNpBsmP4zHB2aurN86RPTaz7uCzDRFfbPKq178HYcf8QK","QmUUn87ggevV2pdwmyBp5yz3dfowCFMwn4mLnQZ3PSbnN5","QmUtEu1CSM9cH8BDstcEg7TZvxWfxW17BMSkth5kRTrY5K","Qme5c5My2uuwJEAFfPoytvXfoex1xdkWUbscCQrNKkPcK5","QmSgwi1MDSLddLVL9hSPrwvneire3AjkoenbLkSCqX5Mk5","QmWVbK2tFpPv4K4bM1R2RCeoWFEhafQyaWFnXo3vLsk64k","Qmcqnfi7cnpBFZoa2vn2JgiXY8RiQUjJ7xReXEpEkju2Ut","QmY6Gz4hZ1wR4J7zjhKvcTGPqPaDqHwaVB4e3LSKaMUo8w","QmSAsgm65uuQQ8zLYEh7Ys9X9AkoNrRTUv4FscNYR1aC89"]}}
main.dc966f9e.js:108 makeExtrinsicCall: updated status :: {"events":[],"status":{"Broadcast":["Qmar8HNVsCovXpmVwn32UPe9yQN6AWYm93rCgThfT7wFec"]}}```

If I encounter the error regarding what I believe to be the nonce, I will post it here.

**Comment by mochet** [comment]
This issue may have been caused because the pioneer server lost sync for a while.
It appears the broadcast attempt never timed out though, even after about an hour.

**Comment by mochet** [comment]
This is the second condition on which a transaction appears as being stuck
![image](https://user-images.githubusercontent.com/50830161/84065370-52c51f80-a9d5-11ea-975a-8b5eedaea786.png)

Console output
```020-06-08 22:12:51        RPC-CORE: submitAndWatchExtrinsic (extrinsic: Extrinsic): ExtrinsicStatus:: 1014: Priority is too low: (20001 vs 20001): The transaction has ```

**Comment by mochet** [comment]
Another stuck transaction error
![image](https://user-images.githubusercontent.com/50830161/87662261-fba03080-c772-11ea-8d71-13c2de7eae49.png)
submitAndWatchExtrinsic (extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Stale

**Comment by phibosGit** [comment]
You time.is and data\time reference and the time zone are sync?
