### ISSUE TITLE
Wrong or unclear information

### ISSUE THREAD

**Issue by finnyfound** [Joystream/helpdesk#69]
For upgrading storage account
`If you have been running a storage node previously, and used .bash_profile to avoid the yarn run prefix, you need to: $ nano ~/.bash_profile Then, uncomment or remove the lines below:`

Its uncomment or remove ,  it shud be `comment or remove`

For running colossus you dont have to pass `ID` `--provider-id` only have to give the number
`DEBUG=* colossus server --key-file <5YourStorageAddress.json> --public-url https://<your.cool.url> --provider-id ID <your_storage-id>`

**Comment by blrhc** [comment]
Thanks, we'll add in these updates as soon as possible.

**Comment by bwhm** [comment]
Thanks, forgot to mention it was fixed by #75
