### ISSUE TITLE
Caddy documentation needs update (storage node)

### ISSUE THREAD

**Issue by mochet** [Joystream/helpdesk#71]
Caddy documentation for storage node no longer works.

Updated binary download:
https://caddyserver.com/docs/download
`$ echo "deb [trusted=yes] https://apt.fury.io/caddy/ /" \`
`    | sudo tee -a /etc/apt/sources.list.d/caddy-fury.list`
`$ sudo apt update`
`$ sudo apt install caddy`

The caddy config formatting has changed a bit (thanks to kekmex for the updated config):
` # Storage Node API`
`<url> {`
`    reverse_proxy localhost:3000`
`    header / {`
`        Access-Control-Allow-Origin  *`
`        Access-Control-Allow-Methods "GET, PUT, HEAD, OPTIONS"`
`    }`
}`

loading the caddyfile is now done using this command, email address is no longer necessary:
`caddy run --config /path/to/Caddyfile`

**Comment by bwhm** [comment]
Thanks for this!
Forgot to assign it to myself, but closed with #75
