### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by oiclid** [Joystream/helpdesk#81]
What is the workflow for contributing to one of repos here? I know different groups have different systems, and I've not been able to find anything detailing Joystream's, so I thought I'd ask first.

**Comment by bwhm** [comment]
Hey,

So sorry for the late reply...
If you find anything that is wrong, create a PR, and we'll review it! There may even be a [bounty](https://testnet.joystream.org/#/forum/threads/216) involved :)
