### ISSUE TITLE
Pull Request

### ISSUE THREAD

**Issue by oiclid** [Joystream/helpdesk#82]
Could someone please grant me permissions to be able to make a PR? I fixed a typo but can't push my branch.

Thanks.

**Comment by bwhm** [comment]
Hey @oiclid, 

I've always found the permissions on github a little difficult to parse, but AFAIK, there are no special permissions needed to make a PR. Did you try and push to this repo, or your own fork?

**Comment by bwhm** [comment]
Closed (see #81)
